stages:
  - build
#  - test

centos:
  image: 'dxfeedcapi/dx-builder-linux:centos-6.10'
  script:
    - chmod +x ./make_ci.sh
    - chmod +x ./make_package.sh
    - chmod +x ./build.sh
    - chmod +x ./scripts/check_build.sh
    - chmod +x ./scripts/combine_package.sh
    - chmod +x ./scripts/run_test.sh
    - mkdir artifacts
    - scl enable devtoolset-2 bash
    - source /opt/rh/devtoolset-2/enable
    - ./make_ci.sh rebuild no-test no-tls
    - for f in ./dxfeed-c-api*.zip; do cp $f ./artifacts; done
    - ./make_ci.sh rebuild no-test
    - for f in ./dxfeed-c-api*.zip; do cp $f ./artifacts; done
  artifacts:
    paths:
      - ./artifacts/dxfeed-c-api*.zip

debian:
  image: 'dxfeedcapi/dx-builder-linux:debian-9'
  script:
    - chmod +x ./make_ci.sh
    - chmod +x ./make_package.sh
    - chmod +x ./build.sh
    - chmod +x ./scripts/check_build.sh
    - chmod +x ./scripts/combine_package.sh
    - chmod +x ./scripts/run_test.sh
    - mkdir artifacts
    - ./make_ci.sh rebuild no-test no-tls
    - for f in ./dxfeed-c-api*.zip; do cp $f ./artifacts; done
    - ./make_ci.sh rebuild no-test
    - for f in ./dxfeed-c-api*.zip; do cp $f ./artifacts; done
  artifacts:
    paths:
      - ./artifacts/dxfeed-c-api*.zip
