stages:
  - build-release
#  - build-debug
  - test

centos:
  image: 'dxfeedcapi/dx-builder-linux:centos-6.10'
  script:
    - mkdir artifacts
    - sudo ./make_ci.sh rebuild no-test no-tls
    - cp build artifacts
    - sudo ./make_ci.sh rebuild no-test
    - cp build artifacts
  artifacts:
    paths:
      - dxfeed-c-api*.zip

debian:
  image: 'dxfeedcapi/dx-builder-linux:debian-9'
  script:
    - mkdir artifacts
    - sudo ./make_ci.sh rebuild no-test no-tls
    - cp build artifacts
    - sudo ./make_ci.sh rebuild no-test
    - cp build artifacts
  artifacts:
    paths:
      - dxfeed-c-api*.zip
