before_script:
#  - git submodule update --init --recursive
  - echo $CI_PROJECT_DIR
  - g++ --version
  - cmake --version

stages:
  - build-release
#  - build-debug
  - test

centos:
  image: 'dxfeedcapi/dx-builder-linux:centos-6.10'
  script:
    - mkdir artifacts
    - ./make_ci.sh rebuild no-test no-tls
    - cp build artifacts
    - ./make_ci.sh rebuild no-test
    - cp build artifacts
  artifacts:
    paths:
      - *.zip

debian:
  image: 'dxfeedcapi/dx-builder-linux:debian-9'
  script:
    - mkdir artifacts
    - ./make_ci.sh rebuild no-test no-tls
    - cp build artifacts
    - ./make_ci.sh rebuild no-test
    - cp build artifacts
  artifacts:
    paths:
      - *.zip