stages:
  - build-release
#  - build-debug
  - test

centos:
  image: 'dxfeedcapi/dx-builder-linux:centos-6.10'
  script:
    - whoami
    - chmod +x ./make_ci.sh
    - chmod +x ./make_package.sh
    - chmod +x ./build.sh
    - chmod +x ./scripts/check_build.sh
    - chmod +x ./scripts/combine_package.sh
    - chmod +x ./scripts/run_test.sh
    - mkdir artifacts
    - ./make_ci.sh rebuild no-test no-tls
    - cp build artifacts
    - ./make_ci.sh rebuild no-test
    - cp build artifacts
  artifacts:
    paths:
      - dxfeed-c-api*.zip

debian:
  image: 'dxfeedcapi/dx-builder-linux:debian-9'
  script:
    - whoami
    - chmod +x ./make_ci.sh
    - chmod +x ./make_package.sh
    - chmod +x ./build.sh
    - chmod +x ./scripts/check_build.sh
    - chmod +x ./scripts/combine_package.sh
    - chmod +x ./scripts/run_test.sh
    - mkdir artifacts
    - ./make_ci.sh rebuild no-test no-tls
    - cp build artifacts
    - ./make_ci.sh rebuild no-test
    - cp build artifacts
  artifacts:
    paths:
      - dxfeed-c-api*.zip
