# action.yml
name: 'GitHub Upload Release Artifacts'
description: 'Upload Artifacts to a GitHub release.'
branding:
  icon: 'upload-cloud'
  color: 'yellow'
inputs:
  draft_regex:
    description: 'regex for draft tag detection'
    default: ''
    required: false
  prerelease_regex:
    description: 'regex for prerelease tag detection'
    default: ''
    required: false
  notes:
    description: "release notes"
runs:
  using: 'docker'
  image: 'Dockerfile'
