# action.yml
name: 'DoxyDoc'
description: 'Build doxygen documentation from project sources'
inputs:
  artifact:
    description: 'generated artifact prefix'
    required: true
  release:
    description: 'artifact version'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
#  args:
#    - ${{ inputs. }}